Convert GNU assembler syntax to Unified Assembler Language (compatible with clang integrated as)
error: instruction 'addlt' can not set flags, but 's' suffix specified
__asm ("addlts  r2, #32");
       ^
<inline asm>:1:2: note: instantiated into assembly here
        addlts  r2, #32
        ^

error: invalid instruction, did you mean: ldrexh, ldrh?
__asm ("ldrgeh  r4, [r0], #2");
       ^
<inline asm>:1:2: note: instantiated into assembly here
        ldrgeh  r4, [r0], #2
        ^~~~~~

error: invalid instruction, did you mean: ldrh, ldrt?
__asm ("ldrgth  r5, [r0], #2");
       ^
<inline asm>:1:2: note: instantiated into assembly here
        ldrgth  r5, [r0], #2

Unfortunately it breaks gcc

(cherry picked from commit 8790b70f5f1e46b48a280eef2ecb9174140433a9)